CREATE DATABASE RESTAURANT_MANGEMENT ;

USE RESTAURANT_MANGEMENT ;

CREATE TABLE OUR_CUSTOMER(
USER_ID varchar(20) PRIMARY KEY,
UPSWD VARCHAR(10) NOT NULL,
UNAME VARCHAR(30) NOT NULL,
UCONTACT CHAR(10) NOT NULL,
ORDER_ID VARCHAR(6) NOT NULL
);

ALTER TABLE OUR_CUSTOMER
ADD CONSTRAINT CK1 CHECK(LENGTH(UCONTACT)=10);

ALTER TABLE OUR_CUSTOMER
ADD CONSTRAINT CK2 CHECK(LENGTH(ORDER_ID)=6);

ALTER TABLE OUR_CUSTOMER
ADD CONSTRAINT U1 UNIQUE(UCONTACT);

ALTER TABLE OUR_CUSTOMER
ADD CONSTRAINT U3 UNIQUE(ORDER_ID);

SELECT * FROM OUR_CUSTOMER ;

CREATE TABLE RESTAURANT_ORDERS(
ORDER_ID VARCHAR(6) NOT NULL ,
TABLENO CHAR(4) NOT NULL ,
ORDER_TIME TIME NOT NULL,
ORDER_DATE DATE NOT NULL,
FOOD_ID CHAR(5) NOT NULL,
FOOD_QUANTITY INT);

SELECT * FROM RESTAURANT_ORDERS ;

CREATE TABLE ONLINE_ORDERS(
ORDER_ID VARCHAR(6) NOT NULL ,
ORDER_TIME TIME NOT NULL,
ORDER_DATE DATE NOT NULL,
FOOD_ID CHAR(5) NOT NULL,
FOOD_QUANTITY INT,
DELIVERY_ADDRESS VARCHAR(50) NOT NULL ,
PAYMENT_MODE VARCHAR(10) NOT NULL,
PAID VARCHAR(10)
);

CREATE TABLE TABLE_BOOKINGS(
USER_ID varchar(20) NOT NULL,
TABLENO CHAR(4) NOT NULL ,
ARRIVAL_DATE DATE NOT NULL,
ARRIVAL_TIME TIME,
NO_OF_PEOPLE INT
);

Alter table table_bookings
add column TABLEID CHAR(4) NOT NULL ;

SELECT * FROM TABLE_BOOKINGS ;

CREATE TABLE TABLE_TYPE(
TABLEId CHAR(4) PRIMARY KEY,
No_of_seats int,
ServiceCharges int
);




